### ISSUE TITLE
Fail to build 

### ISSUE THREAD

**Issue by sv1** [HB9UF/gr-ysf#24]
Hello HB9UF,

I am trying to build gr-ysf on a Debian machine and the compile process fails with a missing file:

$ make
Scanning dependencies of target gnuradio-ysf
[  5%] Building CXX object lib/CMakeFiles/gnuradio-ysf.dir/deframer_bb_impl.cc.o
[ 11%] Building CXX object lib/CMakeFiles/gnuradio-ysf.dir/packets/fich_packet.cc.o
[ 17%] Building CXX object lib/CMakeFiles/gnuradio-ysf.dir/fich_sink_b_impl.cc.o
[ 23%] Building CXX object lib/CMakeFiles/gnuradio-ysf.dir/dch_sink_b_impl.cc.o
[ 29%] Building CXX object lib/CMakeFiles/gnuradio-ysf.dir/demux_planner.cc.o
[ 35%] Building CXX object lib/CMakeFiles/gnuradio-ysf.dir/vd2_vch_decoder_bb_impl.cc.o
[ 41%] Building CXX object lib/CMakeFiles/gnuradio-ysf.dir/mbelib_block_bf_impl.cc.o
In file included from /opt/linux/gr-ysf/lib/mbelib_block_bf_impl.cc:27:0:
/opt/linux/gr-ysf/lib/mbelib_block_bf_impl.h:24:33: fatal error: ysf/mbelib_block_bf.h: No such file or directory
 #include <ysf/mbelib_block_bf.h>
                                 ^
compilation terminated.
lib/CMakeFiles/gnuradio-ysf.dir/build.make:192: recipe for target 'lib/CMakeFiles/gnuradio-ysf.dir/mbelib_block_bf_impl.cc.o' failed
make[2]: **\* [lib/CMakeFiles/gnuradio-ysf.dir/mbelib_block_bf_impl.cc.o] Error 1
CMakeFiles/Makefile2:123: recipe for target 'lib/CMakeFiles/gnuradio-ysf.dir/all' failed
make[1]: **\* [lib/CMakeFiles/gnuradio-ysf.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

Any help would be greatly appreciated

73
de SV1LJJ

**Comment by mweyland** [comment]
Hello and thank you for your report

You found a bug -- I had forgotten to include that file. I'm about to push a fix. If you pull again from git, you should get that file. (If you didn't clone the repo, but went with the zip download, just download the new master and start over with mkdir build, cd build, cmake .. and make).

Chances are that you're the first person apart from me trying this out. I am in the process of putting together a 'getting started' guide but this needs a few more days. I'm just saying that because I don't want this to be a bad first experience. That said, the project is quite young. Feel free to drop me an email if you get stuck. I'm also on IRC if that helps.

Regards and thanks for the report
Matt, HB9FRV

**Comment by sv1** [comment]
Hello Matt,

thank you very much for the quick response!!! I just pulled the git
again and everything compiled perfectly!!!

Regards
Apostolos

On Πεμ, 2015-11-12 at 09:12 -0800, mweyland wrote:

> Hello and thank you for your report
> 
> You found a bug -- I had forgotten to include that file. I'm about to
> push a fix. If you pull again from git, you should get that file. (If
> you didn't clone the repo, but went with the zip download, just
> download the new master and start over with mkdir build, cd build,
> cmake .. and make).
> 
> Chances are that you're the first person apart from me trying this
> out. I am in the process of putting together a 'getting started' guide
> but this needs a few more days. I'm just saying that because I don't
> want this to be a bad first experience. That said, the project is
> quite young. Feel free to drop me an email if you get stuck. I'm also
> on IRC if that helps.
> 
> Regards and thanks for the report
> Matt, HB9FRV
> 
> —
> Reply to this email directly or view it on GitHub.Web Bug from
> https://github.com/notifications/beacon/AFRSQ_BE9r6bJMurmXLRIyojXWNU60U6ks5pFMAPgaJpZM4GhJuZ.gif

## 

Κεφάλας Απόστολος -  SV1LJJ 
Γραμματέας ΕΚΕΑν
Τοπικός Σύνδεσμος Αττικής
τηλ: +30 6979 976 039
Echolink id: 309275
skype: apostolis.kef
sip:apkefalas@iptel.org
PGP: 0xA3C19DA0
